INSERT INTO TB_WORKER (WORKER_NAME, DIALY_INCOME) VALUES ('WALTER', 1000.0);
INSERT INTO TB_WORKER (WORKER_NAME, DIALY_INCOME) VALUES ('MARIA', 600.0);
INSERT INTO TB_WORKER (WORKER_NAME, DIALY_INCOME) VALUES ('DERLEIA', 800.0);
